// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.1
// source: lingua-protos/user_lesson.proto

package genprotos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	UserLessonService_Create_FullMethodName = "/lingua.UserLessonService/Create"
)

// UserLessonServiceClient is the client API for UserLessonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserLessonServiceClient interface {
	Create(ctx context.Context, in *UserLessonCReq, opts ...grpc.CallOption) (*Void, error)
}

type userLessonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserLessonServiceClient(cc grpc.ClientConnInterface) UserLessonServiceClient {
	return &userLessonServiceClient{cc}
}

func (c *userLessonServiceClient) Create(ctx context.Context, in *UserLessonCReq, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, UserLessonService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserLessonServiceServer is the server API for UserLessonService service.
// All implementations must embed UnimplementedUserLessonServiceServer
// for forward compatibility
type UserLessonServiceServer interface {
	Create(context.Context, *UserLessonCReq) (*Void, error)
	mustEmbedUnimplementedUserLessonServiceServer()
}

// UnimplementedUserLessonServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserLessonServiceServer struct {
}

func (UnimplementedUserLessonServiceServer) Create(context.Context, *UserLessonCReq) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserLessonServiceServer) mustEmbedUnimplementedUserLessonServiceServer() {}

// UnsafeUserLessonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserLessonServiceServer will
// result in compilation errors.
type UnsafeUserLessonServiceServer interface {
	mustEmbedUnimplementedUserLessonServiceServer()
}

func RegisterUserLessonServiceServer(s grpc.ServiceRegistrar, srv UserLessonServiceServer) {
	s.RegisterService(&UserLessonService_ServiceDesc, srv)
}

func _UserLessonService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLessonCReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLessonServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserLessonService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLessonServiceServer).Create(ctx, req.(*UserLessonCReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserLessonService_ServiceDesc is the grpc.ServiceDesc for UserLessonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserLessonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lingua.UserLessonService",
	HandlerType: (*UserLessonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserLessonService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lingua-protos/user_lesson.proto",
}
