// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.1
// source: lingua-protos/user.proto

package genprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileGRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string        `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email    string        `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password string        `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	UserData *UserDataGRes `protobuf:"bytes,5,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
}

func (x *ProfileGRes) Reset() {
	*x = ProfileGRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lingua_protos_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileGRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileGRes) ProtoMessage() {}

func (x *ProfileGRes) ProtoReflect() protoreflect.Message {
	mi := &file_lingua_protos_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileGRes.ProtoReflect.Descriptor instead.
func (*ProfileGRes) Descriptor() ([]byte, []int) {
	return file_lingua_protos_user_proto_rawDescGZIP(), []int{0}
}

func (x *ProfileGRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileGRes) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileGRes) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProfileGRes) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProfileGRes) GetUserData() *UserDataGRes {
	if x != nil {
		return x.UserData
	}
	return nil
}

type ProfileUReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *ProfileUReq) Reset() {
	*x = ProfileUReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lingua_protos_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileUReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileUReq) ProtoMessage() {}

func (x *ProfileUReq) ProtoReflect() protoreflect.Message {
	mi := &file_lingua_protos_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileUReq.ProtoReflect.Descriptor instead.
func (*ProfileUReq) Descriptor() ([]byte, []int) {
	return file_lingua_protos_user_proto_rawDescGZIP(), []int{1}
}

func (x *ProfileUReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProfileUReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileUReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type PasswordUReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email    string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PasswordUReq) Reset() {
	*x = PasswordUReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lingua_protos_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasswordUReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordUReq) ProtoMessage() {}

func (x *PasswordUReq) ProtoReflect() protoreflect.Message {
	mi := &file_lingua_protos_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordUReq.ProtoReflect.Descriptor instead.
func (*PasswordUReq) Descriptor() ([]byte, []int) {
	return file_lingua_protos_user_proto_rawDescGZIP(), []int{2}
}

func (x *PasswordUReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PasswordUReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PasswordUReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_lingua_protos_user_proto protoreflect.FileDescriptor

var file_lingua_protos_user_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6c, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x69, 0x6e, 0x67,
	0x75, 0x61, 0x1a, 0x18, 0x6c, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x76, 0x6f, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x6c, 0x69,
	0x6e, 0x67, 0x75, 0x61, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x01, 0x0a, 0x0b,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x47, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x31, 0x0a, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c,
	0x69, 0x6e, 0x67, 0x75, 0x61, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x47, 0x52,
	0x65, 0x73, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4f, 0x0a, 0x0b,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x50, 0x0a,
	0x0c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x55, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x32,
	0xae, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x31, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x0c, 0x2e,
	0x6c, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x2e, 0x42, 0x79, 0x49, 0x44, 0x1a, 0x13, 0x2e, 0x6c, 0x69,
	0x6e, 0x67, 0x75, 0x61, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x47, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x34, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x6c, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x2e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x55, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x6c, 0x69, 0x6e, 0x67, 0x75,
	0x61, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x2e, 0x6c, 0x69, 0x6e,
	0x67, 0x75, 0x61, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x55, 0x52, 0x65, 0x71,
	0x1a, 0x0c, 0x2e, 0x6c, 0x69, 0x6e, 0x67, 0x75, 0x61, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lingua_protos_user_proto_rawDescOnce sync.Once
	file_lingua_protos_user_proto_rawDescData = file_lingua_protos_user_proto_rawDesc
)

func file_lingua_protos_user_proto_rawDescGZIP() []byte {
	file_lingua_protos_user_proto_rawDescOnce.Do(func() {
		file_lingua_protos_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_lingua_protos_user_proto_rawDescData)
	})
	return file_lingua_protos_user_proto_rawDescData
}

var file_lingua_protos_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_lingua_protos_user_proto_goTypes = []any{
	(*ProfileGRes)(nil),  // 0: lingua.ProfileGRes
	(*ProfileUReq)(nil),  // 1: lingua.ProfileUReq
	(*PasswordUReq)(nil), // 2: lingua.PasswordUReq
	(*UserDataGRes)(nil), // 3: lingua.UserDataGRes
	(*ByID)(nil),         // 4: lingua.ByID
	(*Void)(nil),         // 5: lingua.Void
}
var file_lingua_protos_user_proto_depIdxs = []int32{
	3, // 0: lingua.ProfileGRes.user_data:type_name -> lingua.UserDataGRes
	4, // 1: lingua.UserService.GetProfile:input_type -> lingua.ByID
	1, // 2: lingua.UserService.UpdateProfile:input_type -> lingua.ProfileUReq
	2, // 3: lingua.UserService.UpdatePassword:input_type -> lingua.PasswordUReq
	0, // 4: lingua.UserService.GetProfile:output_type -> lingua.ProfileGRes
	5, // 5: lingua.UserService.UpdateProfile:output_type -> lingua.Void
	5, // 6: lingua.UserService.UpdatePassword:output_type -> lingua.Void
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_lingua_protos_user_proto_init() }
func file_lingua_protos_user_proto_init() {
	if File_lingua_protos_user_proto != nil {
		return
	}
	file_lingua_protos_void_proto_init()
	file_lingua_protos_user_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_lingua_protos_user_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ProfileGRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lingua_protos_user_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ProfileUReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lingua_protos_user_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*PasswordUReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lingua_protos_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lingua_protos_user_proto_goTypes,
		DependencyIndexes: file_lingua_protos_user_proto_depIdxs,
		MessageInfos:      file_lingua_protos_user_proto_msgTypes,
	}.Build()
	File_lingua_protos_user_proto = out.File
	file_lingua_protos_user_proto_rawDesc = nil
	file_lingua_protos_user_proto_goTypes = nil
	file_lingua_protos_user_proto_depIdxs = nil
}
